### PR TITLE
Update luhmanns-zettel-translated.md

### PR DESCRIPTION
**Pull request by arcturus140**
Changing ghost into mind. The mind refers to the mental frame, while ghost is the soul of a dead person.

### CODE REVIEW

**Comment by DivineDominion** [comment]
Interesting, and thanks again for participating!

I do believe that `Geist im Kasten?` could very well mean something along the lines of "Ghost in the shell". But I do see how you came up with that, even though I never thought of this :) 

(I'd personally be inclined to leave "Ghost in the box?", as if it was possessed, but add a footnote/popup with your interpretation, and that both are somewhat present at the same time.)

Again, I'll ask @SaschaFast for feedback.

**Comment by SaschaFast** [comment]
> @arcturus140 
> Changing ghost into mind. The mind refers to the mental frame, while ghost is the soul of a dead person.

I wrote the first commentary on this translation. What do your think about that reasoning?

> In German, "Geist" means both "mind" and "ghost". The question spelled out could be something like "Can the mind of the Zettelkasten be observed?" Or something like that. So, why "ghost" instead of "mind?" 
> 
> There is great anime film titled "Ghost in the Shell". It is quite a philosophical movie that asks the question: If your consciousness can be moved from your body and brain to machine are you still considered a human or will you become a computer program? One possible answer could be: If *we* can move from body to body, and we are still considered human we should be considered to be ghosts that take possession of bodies. 
> 
> What do the visitors see when they see everything and are disappointed? Perhaps, they feel the same disappointment of scientists who opened the scull of people to look at the human mind but see "it all": just flabby gray tissue.
> 
> To this day, this seems to be the feeling us who start their own Zettelkasten. The frankensteinian fantasy of creating something alive turns into obsession or disappointment. The mind of the Zettelkasten turns into a ghost, something ethereal and evasive that can hide in plain sight. We dive into our Zettelkastens in search for what we believe we created and just seem to find notes.
> 
> So, what is *the* Zettelkasten? One possible answer might be: The ghost that is able to hide in plain sight and just can be seen from the corner of the eye.

**Comment by DivineDominion** [comment]
Pinging @arcturus140 to be safe :)

**Comment by arcturus140** [comment]
Thank you for the input. I need to think about this for a bit. I'll give a reply later in the forum.

**Comment by DivineDominion** [comment]
@arcturus140 We've picked up the discussion here in the latest blog post, thanks again for your contribution! https://zettelkasten.de/posts/ghost-in-the-box/

**Pull request closed without merging**
